### ISSUE TITLE
call_bestordersort.m does not work

### ISSUE THREAD

**Issue by qlahcim** [Proteek/Best-Order-Sort#1]
The call_bestordersort.m produce the following error:

`>> call_bestordersort
Undefined function or variable 'BestOrderSort'.
Error in call_bestordersort (line 43)
method = BestOrderSort;`

OS: Win7pro 64bit + Matlab R2016b

**Comment by ghost** [comment]
HI, 
Have you downloaded the bos.jar file and placed it in the same folder? Let me know.

I have the same OS with matlab 2016b and java 1.8.
Thanks.
Sincerely,Proteek
Sent from Yahoo Mail on Android 
 
  On Tue, Feb 28, 2017 at 1:46 PM, Michal Kvasnicka<notifications@github.com> wrote:   
The call_bestordersort.m produce the following error:

>> call_bestordersort Undefined function or variable 'BestOrderSort'. Error in call_bestordersort (line 43) method = BestOrderSort;

OS: Win7pro 64bit + Matlab R2016b

**Comment by qlahcim** [comment]
Yes of course. I download the whole master copy (ZIP file) from your github

`
> pwd
ans =
C:\Users\Misak\Desktop\Best-Order-Sort-master
> dir
.                     BestOrderSort.java    bos.jar               cloud_10000_10_1.txt  
..                    README.md             call_bestordersort.m  
`

**Comment by qlahcim** [comment]
ver
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: ------
Operating System: Microsoft Windows 7 Ultimate  Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

MATLAB                                                Version 9.1         (R2016b)

**Comment by ghost** [comment]
Oh. It will not work with java 1.7. Can you change your MATLAB_HOME to be java 1.8?
Sent from Yahoo Mail on Android 
 
  On Tue, Feb 28, 2017 at 1:59 PM, Michal Kvasnicka<notifications@github.com> wrote:   
ver
MATLAB Version: 9.1.0.441655 (R2016b)
MATLAB License Number: ------
Operating System: Microsoft Windows 7 Ultimate Version 6.1 (Build 7601: Service Pack 1)
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

MATLAB Version 9.1 (R2016b)

**Comment by qlahcim** [comment]
You mean JAVA_HOME instead of MATLAB_HOME?

**Comment by ghost** [comment]
Make a path variable "MATLAB_JAVA" and set its value as this  "C:\Program Files\Java\jre1.8.0_111" which is java 1.8 runtime environment. Check java version after restarting MATLAB, by typing "version -java" in MATLAB command window. Please let me know if it helps.

**Comment by qlahcim** [comment]
Are you sure to use MATLAB_JAVA variable? 

See:
https://www.mathworks.com/help/compiler_sdk/java/configure-your-java-environment.html

**Comment by ghost** [comment]
Yes, I configured it. You can follow that link. Thanks.

**Comment by qlahcim** [comment]
OK ... now everything works like charm :) !!! Thanks
