### ISSUE TITLE
java dependence

### ISSUE THREAD

**Issue by qlahcim** [Proteek/Best-Order-Sort#2]
Is really necessarily to use Java 1.8+ , which is not default java supported by Matlab? 
Will be possible to creata BOS java code compatible with java version 1.7?

Michal

**Comment by qlahcim** [comment]
I try to understand the differences between java 1.7 and 1.8, and I realize that backward compatibility of your code with java 1.7 is difficult problem. I am right? 

In this case is probably impossible to simply transform your code to be compatible with java 1.7 (default java engine for MATLAB R2016b).

The main problem is, that MATLAB with java 1.8 shows a lot of incompatibility problems with its many internal functions (mostly with GUI). So, java 1.8 is not very good choice for MATLAB in general.

**Comment by ghost** [comment]
It is possible. I only need to recompile it with java 1.7 and make jar file. I provided the source code. You can also do that if you want. I will do that shortly.

**Comment by qlahcim** [comment]
Are there any serious reasons to preference java 1.8 ? Better performance, for example?

If not, the version fully compatible with current MAtlab java version is definitely better!

**Comment by ghost** [comment]
The only reason is Java 1.8 is installed in my computer. I will recompile and distribute.
