### ISSUE TITLE
matlab BOS function + documentaion

### ISSUE THREAD

**Issue by qlahcim** [Proteek/Best-Order-Sort#4]
Could be possible to create fully functional matlab wrapper function to call BOS java function directly from MATLAB + some documentation (help) for BOS function (description input and output variables)?

**Comment by ghost** [comment]
We have optimized BOS function which is much faster than BOS in some cases. We will submit the paper by this summer and upload the code. I am planning to make warapper function then. And also implement in C/C++

**Comment by qlahcim** [comment]
I am really highly interested to test your new (optimized) BOS function. If you are willing to share your code with me, I will be happy to help you with thorough testing.
