### ISSUE TITLE
populatuion with duplicated rows

### ISSUE THREAD

**Issue by qlahcim** [Proteek/Best-Order-Sort#5]
In the case of duplicated population rows your code did not processed these duplicities correctly.

See example:
populatuion = [ 1 1; 1 1; 1 1; 2 2]

Expected result is:
1
1
1
0

But your code produce in this case the following wrong result:
1
2
3
0

Note: this problem occurs only for size(population,2) = 2
Could you please take a look on this problem?

**Comment by ghost** [comment]
Let me check this.

**Comment by ghost** [comment]
Bug fixed, I will upload it shortly.

**Comment by qlahcim** [comment]
Great! Thanks a lot...

**Comment by ghost** [comment]
The original number of front would be 2 for your example, as [1 1] cannot dominate [1 1] (should be better in at least one objective). I have uploaded the jar file. But compiled with Java 1.8

**Comment by qlahcim** [comment]
When do you plan to upload the fixed version of BOS compiled by Java 1.7?

**Comment by ghost** [comment]
I have uploaded the compiled file. Change the caller matlab file accordingly i.e. javaaddpath(fullfile(pwd,'bos_1.7.jar'));

**Comment by qlahcim** [comment]
Thank you very much.
