### ISSUE TITLE
NaN values in population

### ISSUE THREAD

**Issue by qlahcim** [Proteek/Best-Order-Sort#6]
Will be possible to modify your algorithm to process NaN values in population?
Population rows with any NaN should be ranked by "-1".

See example:
population =

     1     1     1
     1     1     1
     2     2     2
     0  NaN   1

BOS result
I.R = 
    1
    1
    0
   -1

**Comment by ghost** [comment]
You can use matlab script to find NaN rows and NDS for non-nan values

**Comment by qlahcim** [comment]
Is that really so simple?

**Comment by ghost** [comment]
Because non-dominated sorting for NaN is not defined.
