### ISSUE TITLE
Max Pareto rank number

### ISSUE THREAD

**Issue by qlahcim** [Proteek/Best-Order-Sort#7]
And the last request: Could be possible to add one additional input parameter ... rankMax to define maximum pareto rank computed by BOS. In many practical cases is required to compute only few first pareto fronts. 

Due to  this modification should be slightly modified the output results I.R variable
I.R  = 1, ..., rankMax for population items on corresponding pareto fronts 
I.R = 0 for other population items
I.R = -1 for population items with any NaN values

**Comment by qlahcim** [comment]
Ok ... I just want to know how difficult could be to modify the BOS to compute not all pareto fronts but pareto front ranks < rankMax only?

**Comment by ghost** [comment]
This algorithm is fast when you have many fronts. It doesnt find front by front which would be slower. So it is better to get all the ranks. But it is possible to stop when there is a guarantee that no other points can be within max rank. I can include that in the optimized version. It is not finalized and you have to wait till summer. Thanks.

**Comment by qlahcim** [comment]
Thanks for response! I will wait for your next version. In the mean time is your current BOS code the fastest available pareto sorting method. Thanks again for sharing!

**Comment by ghost** [comment]
Thank you for using the code. Have you tried other methods of pareto sorting?

**Comment by qlahcim** [comment]
Yes, I tried a few Matlab codes (Mathworks FEX ), but all these codes are probably methodically very similar. Could you recommend me some links on available pareto sorting codes? Of course I prefer Matlab compatible codes (M files, Mex, ...)

**Comment by ghost** [comment]
I don't have MATLAB files. I have implemented other algorithms in java. If you use m-files, it will be much slower.

**Comment by qlahcim** [comment]
Is possible to call your other java codes from Matlab like BOS? If yes, I will be happy to test it.

**Comment by ghost** [comment]
Actually I checked those and reported in my paper. And those are slower than BOS in general.

**Comment by qlahcim** [comment]
OK ... I am agree with you! BOS is recently fastest pareto sorting algorithm. I am looking forward your "optimized" C++ BOS version with MATLAB wrapper. Please let me know about any progress on this topic. Thanks again, Michal
